name: simple-build-deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
      uses: brian-rose/cookbook-actions/.github/workflows/build-book.yaml@myst
      with:
        build_command: 'myst build --execute --html'
    
    deploy:
        needs: build
        uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
